version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/site1-public:/var/www/html/site1-public
      - ./nginx/site2-restricted:/var/www/html/site2-restricted
      - ./nginx/site.conf:/etc/nginx/sites-available/site.conf
      - ./nginx/site_certificate.crt:/etc/ssl/certs/site_certificate.crt
      - ./nginx/site_private.key:/etc/ssl/private/site_private.key
